runs:
  using: Composite
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Setup Salesforce CLI
      shell: bash
      run: npm i @salesforce/cli -g
