name: Create scratch org

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - feature/**

jobs:
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup Salesforce CLI
        shell: bash
        run: npm i @salesforce/cli -g

      - name: Result
        shell: bash
        run: |
          pwd
          git branch

      - name: Authenticate DevHub
        shell: bash
        run: |
          mkdir ./temp
          echo -n ${{ secrets.SECRET_KEY }} | base64 -d > ./temp/server.key
          cat ./temp/server.key
          sf org login jwt -r ${{ secrets.INSTANCE_URL }} -i ${{ secrets.CLIENT_ID }} -f ./temp/server.key
