name: Create scratch org

on:
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Node
        run: npm --v
        shell: bash