name: Create scratch org

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - feature/**

jobs:
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Dump
        uses: ./.github/actions/dump

      - name: Make temp directory
        shell: bash
        run: mkdir ./temp

      - name: Setup Salesforce CLI
        uses: ./.github/actions/setup-sf

      - name: Authenticate DevHub
        shell: bash
        run: |
          echo -n ${{ secrets.SECRET_KEY }} | base64 -d > ./temp/server.key
          sf org login jwt -r ${{ secrets.INSTANCE_URL }} -o ${{ secrets.INTEGRATION_USERNAME }} -i ${{ secrets.CLIENT_ID }} -f ./temp/server.key -a devhub

      - name: Create scratch org
        shell: bash
        run: ./scripts/setup_scratch.sh devhub scratch -y 30 -w 15 --json
