name: Create scratch org

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - feature/**

jobs:
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup Salesforce CLI
        shell: bash
        run: npm i @salesforce/cli -g

      - name: Result
        shell: bash
        run: |
          pwd
          git branch

      - name: Authenticate DevHub
        shell: bash
        run: |
          access_token=$(\
            curl -X POST "${{ secrets.INSTANCE_URL }}/services/oauth2/token?grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}" | \
            jq -r .access_token \
          )
          sf org create scratch -f config/project-scratch-def.json --target-dev-hub ${access_token} --alias scratch
